FEATURE_SCHEMA = [

    # --- A. Process, Memory & Execution ---
    "API_PROC_CREATE","API_PROC_TERMINATE","API_THREAD_CREATE",
    "API_THREAD_SUSPEND_RESUME","API_REMOTE_THREAD","API_PROCESS_ENUM",
    "API_THREAD_ENUM","API_MEMORY_ALLOC","API_MEMORY_PROTECT",
    "API_MEMORY_READ","API_MEMORY_WRITE","API_SECTION_MAP",
    "API_SECTION_UNMAP","API_DLL_LOAD","API_DLL_UNLOAD",
    "API_GET_PROC_ADDR","API_EXCEPTION_HANDLER","API_CONTEXT_MANIPULATION",

    # --- B. Crypto ---
    "API_CRYPTO_CONTEXT","API_CRYPTO_KEY_GEN","API_CRYPTO_KEY_EXPORT",
    "API_CRYPTO_HASH","API_CRYPTO_ENCRYPT","API_CRYPTO_DECRYPT",
    "API_CERT_OPEN_STORE","API_CERT_CONTROL","API_CERT_SYSTEM_STORE",
    "API_DATA_DECOMPRESSION",

    # --- C. File System ---
    "API_FILE_CREATE","API_FILE_OPEN","API_FILE_READ","API_FILE_WRITE",
    "API_FILE_DELETE","API_FILE_RENAME","API_FILE_ATTRIBUTES",
    "API_FILE_SIZE_QUERY","API_DIRECTORY_ENUM","API_DIRECTORY_CREATE",
    "API_DIRECTORY_DELETE","API_TEMP_PATH_ACCESS",

    # --- D. Network ---
    "API_SOCKET_CREATE","API_SOCKET_CONNECT","API_SOCKET_BIND_LISTEN",
    "API_SOCKET_SEND","API_SOCKET_RECV","API_SOCKET_CLOSE",
    "API_DNS_QUERY","API_HTTP_OPEN","API_HTTP_REQUEST",
    "API_HTTP_STATUS_QUERY",

    # --- E. Anti-analysis ---
    "API_DEBUG_DETECTION","API_DELAY_EXECUTION","API_KEYBOARD_STATE",
    "API_WINDOW_ENUMERATION","API_HOOK_INSTALL","API_ERROR_MODE_CONTROL",

    # --- F. Registry ---
    "REG_AUTORUN_MOD","REG_SERVICE_CREATE_DELETE","REG_SERVICE_START_STOP",
    "REG_KEY_CREATE","REG_KEY_DELETE","REG_VALUE_SET","REG_VALUE_DELETE",
    "REG_ENUM_KEYS","REG_CLSID_ACTIVITY","REG_FILE_ASSOC_CHANGE",
    "REG_SECURITY_POLICY","REG_USER_PROFILE_MOD",

    # --- G. DROP ---
    "DROP_EXECUTABLE_FILES","DROP_ENCRYPTED_EXTENSIONS","DROP_ARCHIVES",
    "DROP_DOCUMENT_FILES","DROP_MEDIA_FILES","DROP_SCRIPT_FILES",
    "DROP_LIBRARY_FILES","DROP_CONFIG_FILES","DROP_TEMP_FILES",
    "DROP_RANDOM_NAMED_FILES",

    # --- H. System ---
    "API_SYSTEM_INFO","API_DISK_SPACE_QUERY","API_VOLUME_ENUM",
    "API_ADAPTER_INFO","API_USERNAME_QUERY","API_COMPUTER_NAME_QUERY",

    # --- I. Special ---
    "ANOMALY_INDICATOR","EXCEPTION_TRIGGERED",

    # =========================================================
    # NEW BEHAVIORAL ENTROPY FEATURES
    # =========================================================
    "FILE_ENTROPY",
    "AVG_SECTION_ENTROPY",
    "HAS_HIGH_ENTROPY_SECTION",
    "MAX_SECTION_ENTROPY",
    "MIN_SECTION_ENTROPY",
    "SECTION_ENTROPY_STD",
    "NUM_HIGH_ENTROPY_SECTIONS",
    "TEXT_SECTION_ENTROPY",
    "RSRC_SECTION_ENTROPY",
    "NUM_IMPORTS",

    # =========================================================
    # NEW ARTIFACT STRUCTURAL FEATURES
    # =========================================================
    "LOW_IMPORT_COUNT",
    "SMALL_IMPORT_TABLE",
    "HIGH_ENTROPY_PACKING",
    "FEW_SECTIONS",
    "LARGE_RESOURCE_SECTION",
    "ENTRYPOINT_OUTSIDE_TEXT",
    "UNUSUAL_SECTION_NAMES",

    # =========================================================
    # NEW RANSOMWARE STRING FEATURES
    # =========================================================
    "RANSOM_NOTE_STRINGS",
    "CRYPTO_FILE_EXTENSION_STRINGS",
    "WALLPAPER_CHANGE_STRINGS",

    # =========================================================
    # NEW DIGITAL SIGNATURE FEATURES
    # =========================================================
    "HAS_DIGITAL_SIGNATURE",
    "IS_SIGNATURE_VALID",

    
    # --- A. Process, Memory & Execution ---
    "API_PRIVILEGE_ESC",
    "API_MUTEX",
    "API_SYSTEM_SHUTDOWN",

    # --- NEW ARTIFACT STRUCTURAL FEATURES ---
    "IS_GUI_APP",
    "IS_CONSOLE_APP",
    "HAS_OVERLAY",
    "VIRTUAL_RAW_SIZE_ANOMALY",

    # --- NEW RANSOMWARE STRING FEATURES ---
    "SHADOW_COPY_DELETION_STRINGS",
]